# Generated by Django 4.0.3 on 2022-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voters_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('efingerid', models.CharField(max_length=15)),
                ('eaddress', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'voters_list',
            },
        ),
    ]
